
-- This file is auto-generated by tts_export.ps1 from PrivateAuras.csv
-- Do not edit manually. Re-run the export script to regenerate.

local LSM = LibStub("LibSharedMedia-3.0")
local SOUND = LSM.MediaType and LSM.MediaType.SOUND or "sound"
local addonPath = "Interface\\AddOns\\BigWigs_Yvairels_VoicePack\\Sounds\\"
local COLOR = "|cff9b59b6"

local sounds = {
	{"The Dreamrift - Chimaerus: Alnsight", "The_Dreamrift-1245698-Alnsight.ogg"},
	{"The Dreamrift - Chimaerus: Rift Madness", "The_Dreamrift-1264756-Rift_Madness.ogg"},
	{"The Dreamrift - Chimaerus: Consuming Miasma", "The_Dreamrift-1257087-Consuming_Miasma.ogg"},
	{"The Voidspire - Crown: Silverstrike Arrow", "The_Voidspire-1233602-Silverstrike_Arrow.ogg"},
	{"The Voidspire - Crown: Grasp of Emptiness", "The_Voidspire-1232470-Grasp_of_Emptiness.ogg"},
	{"The Voidspire - Crown: Void Expulsion", "The_Voidspire-1283236-Void_Expulsion.ogg"},
	{"The Voidspire - Crown: Ranger Captain's Mark", "The_Voidspire-1237623-Ranger_Captains_Mark.ogg"},
	{"The Voidspire - Crown: Aspect of the End", "The_Voidspire-1239111-Aspect_of_the_End.ogg"},
	{"The Voidspire - Crown: Dark Rush", "The_Voidspire-1238708-Dark_Rush.ogg"},
	{"The Voidspire - Salhadaar: Void Infusion", "The_Voidspire-1245960-Void_Infusion.ogg"},
	{"The Voidspire - Salhadaar: Shattering Twilight", "The_Voidspire-1253024-Shattering_Twilight.ogg"},
	{"The Voidspire - Salhadaar: Despotic Command", "The_Voidspire-1248697-Despotic_Command.ogg"},
	{"The Voidspire - Averzian: Black Miasma", "The_Voidspire-1275059-Black_Miasma.ogg"},
	{"The Voidspire - Averzian: Umbral Collapse", "The_Voidspire-1249265-Umbral_Collapse.ogg"},
	{"The Voidspire - Averzian: Void Marked", "The_Voidspire-1280023-Void_Marked.ogg"},
	{"The Voidspire - Averzian: March of the Endless", "The_Voidspire-1260981-March_of_the_Endless.ogg"},
	{"The Voidspire - Averzian: Blackening Wounds", "The_Voidspire-1265540-Blackening_Wounds.ogg"},
	{"The Voidspire - Averzian: Weakened", "The_Voidspire-1283069-Weakened.ogg"},
	{"The Voidspire - Vanguard: Avenger's Shield", "The_Voidspire-1246487-Avengers_Shield.ogg"},
	{"The Voidspire - Vanguard: Tyr's Wrath", "The_Voidspire-1248721-Tyrs_Wrath.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Nullzone", "The_Voidspire-1244672-Nullzone.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Nullzone Implosion", "The_Voidspire-1252157-Nullzone_Implosion.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Dread Breath", "The_Voidspire-1255612-Dread_Breath.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Tail Lash", "The_Voidspire-1264467-Tail_Lash.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Gloomtouched", "The_Voidspire-1245554-Gloomtouched.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Void Howl", "The_Voidspire-1245059-Void_Howl.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Impale", "The_Voidspire-1265152-Impale.ogg"},
	{"The Voidspire - Vaelgor & Ezzorak: Shadowmark", "The_Voidspire-1270497-Shadowmark.ogg"},
	{"The Voidspire - Vorasius: Fixate", "The_Voidspire-1254113-Fixate.ogg"},
}

for _, entry in next, sounds do
	LSM:Register(SOUND, COLOR .. entry[1] .. "|r", addonPath .. entry[2])
end
